"""density author_id

Revision ID: 3a17c5d928e4
Revises: 8a62394662c0
Create Date: 2026-07-13 05:14:54.232350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a17c5d928e4'
down_revision: Union[str, None] = '8a62394662c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('density_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.BigInteger(), nullable=True))
        batch_op.create_index(batch_op.f('ix_density_reports_author_id'), ['author_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('density_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_density_reports_author_id'))
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###
