"""initial schema

Revision ID: 8a62394662c0
Revises: 
Create Date: 2026-07-12 12:19:30.100888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a62394662c0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('density_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('point', sa.String(length=128), nullable=False),
    sa.Column('couriers', sa.Integer(), nullable=False),
    sa.Column('wait', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('author', sa.String(length=64), nullable=False),
    sa.Column('created_ms', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('density_reports', schema=None) as batch_op:
        batch_op.create_index('ix_density_city_created', ['city', 'created_ms'], unique=False)
        batch_op.create_index(batch_op.f('ix_density_reports_city'), ['city'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=48), nullable=False),
    sa.Column('user_name', sa.String(length=64), nullable=False),
    sa.Column('meta', sa.Text(), nullable=False),
    sa.Column('created_ms', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_created_ms'), ['created_ms'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_user_name'), ['user_name'], unique=False)

    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('user_name', sa.String(length=64), nullable=False),
    sa.Column('created_ms', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mentors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('handle', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mentors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mentors_handle'), ['handle'], unique=False)

    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('handle', sa.String(length=64), nullable=False),
    sa.Column('group', sa.String(length=16), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('start_ms', sa.BigInteger(), nullable=False),
    sa.Column('week2', sa.Boolean(), nullable=False),
    sa.Column('d30', sa.Boolean(), nullable=False),
    sa.Column('checklist_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partner_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('area', sa.String(length=128), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('author', sa.String(length=64), nullable=False),
    sa.Column('created_ms', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('partner_requests', schema=None) as batch_op:
        batch_op.create_index('ix_partner_city_created', ['city', 'created_ms'], unique=False)
        batch_op.create_index(batch_op.f('ix_partner_requests_city'), ['city'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('handle', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('start_ms', sa.BigInteger(), nullable=True),
    sa.Column('mentor_id', sa.Integer(), nullable=True),
    sa.Column('week2', sa.Boolean(), nullable=False),
    sa.Column('d30', sa.Boolean(), nullable=False),
    sa.Column('checklist_json', sa.Text(), nullable=False),
    sa.Column('created_ms', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_user_role_city', ['role', 'city'], unique=False)
        batch_op.create_index('ix_user_role_mentor', ['role', 'mentor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_mentor_id'), ['mentor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_telegram_id'), ['telegram_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_telegram_id'))
        batch_op.drop_index(batch_op.f('ix_users_mentor_id'))
        batch_op.drop_index(batch_op.f('ix_users_city'))
        batch_op.drop_index('ix_user_role_mentor')
        batch_op.drop_index('ix_user_role_city')

    op.drop_table('users')
    with op.batch_alter_table('partner_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partner_requests_city'))
        batch_op.drop_index('ix_partner_city_created')

    op.drop_table('partner_requests')
    op.drop_table('participants')
    with op.batch_alter_table('mentors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mentors_handle'))

    op.drop_table('mentors')
    op.drop_table('feedback')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_user_name'))
        batch_op.drop_index(batch_op.f('ix_events_name'))
        batch_op.drop_index(batch_op.f('ix_events_created_ms'))

    op.drop_table('events')
    with op.batch_alter_table('density_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_density_reports_city'))
        batch_op.drop_index('ix_density_city_created')

    op.drop_table('density_reports')
    # ### end Alembic commands ###
